name: Publish to NPM
on:
  push:
    paths:
      - 'package.json'
    branches:
      - main
jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          standalone: true
          run_install: false


      - name: Install Dependencies
        shell: bash
        run: pnpm i

      - name: Typecheck
        run: pnpm exec tsc

      - name: Lint
        run: pnpm run lint:check

      - name: Run Tests
        run: pnpm run test --run --reporter=verbose

      - name: SetupAuth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package on NPM 📦
        run: pnpm publish -r
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prune PNPM Cache
        run: pnpm store prune
